//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VyukaHN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VyukaHN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h
        ///c1
        ///d1
        ///e1
        ///f1
        ///g1
        ///a1
        ///h1
        ///c2
        ///d2
        ///e2
        ///f2
        ///g2
        ///a2
        ///.
        /// </summary>
        internal static string BasicTones {
            get {
                return ResourceManager.GetString("BasicTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h;185;122;87
        ///c1;181;230;29
        ///d1;255;242;0
        ///e1;195;195;195
        ///f1;237;28;36
        ///g1;153;217;234
        ///a1;255;127;39
        ///h1;255;174;201
        ///c2;127;127;127
        ///d2;255;201;14
        ///e2;63;72;204
        ///f2;34;177;76
        ///g2;163;73;164
        ///a2;112;146;190
        ///.
        /// </summary>
        internal static string BasicTonesMask {
            get {
                return ResourceManager.GetString("BasicTonesMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap becko {
            get {
                object obj = ResourceManager.GetObject("becko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap becko2 {
            get {
                object obj = ResourceManager.GetObject("becko2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap becko2Button {
            get {
                object obj = ResourceManager.GetObject("becko2Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap becko3 {
            get {
                object obj = ResourceManager.GetObject("becko3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap becko3Button {
            get {
                object obj = ResourceManager.GetObject("becko3Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beckoButton {
            get {
                object obj = ResourceManager.GetObject("beckoButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bezPosuvkyButton {
            get {
                object obj = ResourceManager.GetObject("bezPosuvkyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bé;h;1
        ///h;his;1
        ///his;hisis;1
        ///hisis;hisisis;1
        ///h;c1;1
        ///his;c1;1
        ///c1;d1;2
        ///c1;cis1;1
        ///c1;ces1;-1
        ///cis1;d1;1
        ///cis1;cisis1;1
        ///cisis1;cisisis1;1
        ///ces1;c1;1
        ///ces1;ceses1;-1
        ///ceses1;ceseses1;-1
        ///d1;e1;2
        ///d1;dis1;1
        ///d1;des1;-1
        ///dis1;e1;1
        ///dis1;disis1;1
        ///disis1;disisis1;1
        ///des1;d1;1
        ///des1;deses1;-1
        ///deses1;deseses1;-1
        ///e1;f1;1
        ///e1;eis1;1
        ///e1;es1;-1
        ///eis1;f1;0
        ///eis1;eisis1;1
        ///eisis1;eisisis1;1
        ///es1;e1;1
        ///es1;eses1;-1
        ///eses1;eseses1;-1
        ///f1;g1;2
        ///f1;fis1;1
        ///f1;fes1;-1
        ///fis1;g1;1
        ///fis1;fisis1;1
        ///fisis1;fisisis1;1
        ///fes1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DistancesOfTones {
            get {
                return ResourceManager.GetString("DistancesOfTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to č;1;0
        ///zv;1;1
        ///zm;2;0
        ///m;2;1
        ///v;2;2
        ///zv;2;3
        ///zm;3;2
        ///m;3;3
        ///v;3;4
        ///zv;3;5
        ///zm;4;4
        ///č;4;5
        ///zv;4;6
        ///zm;5;6
        ///č;5;7
        ///zv;5;8
        ///zm;6;7
        ///m;6;8
        ///v;6;9
        ///zv;6;10
        ///zm;7;9
        ///m;7;10
        ///v;7;11
        ///zv;7;12
        ///č;8;12
        ///.
        /// </summary>
        internal static string Intervals {
            get {
                return ResourceManager.GetString("Intervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap krizik {
            get {
                object obj = ResourceManager.GetObject("krizik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap krizik2 {
            get {
                object obj = ResourceManager.GetObject("krizik2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap krizik2Button {
            get {
                object obj = ResourceManager.GetObject("krizik2Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap krizik3 {
            get {
                object obj = ResourceManager.GetObject("krizik3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap krizik3Button {
            get {
                object obj = ResourceManager.GetObject("krizik3Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap krizikButton {
            get {
                object obj = ResourceManager.GetObject("krizikButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lockedButtonBackground {
            get {
                object obj = ResourceManager.GetObject("lockedButtonBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nota {
            get {
                object obj = ResourceManager.GetObject("nota", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notaPomocna {
            get {
                object obj = ResourceManager.GetObject("notaPomocna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notaPomocna2 {
            get {
                object obj = ResourceManager.GetObject("notaPomocna2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap osnova {
            get {
                object obj = ResourceManager.GetObject("osnova", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap osnovaBezCiar {
            get {
                object obj = ResourceManager.GetObject("osnovaBezCiar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap osnovaBezCiarVelka {
            get {
                object obj = ResourceManager.GetObject("osnovaBezCiarVelka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap osnovaMaska {
            get {
                object obj = ResourceManager.GetObject("osnovaMaska", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pomocnaLinka {
            get {
                object obj = ResourceManager.GetObject("pomocnaLinka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cis dur;cis1;7
        ///Fis dur;fis1;6
        ///H dur;h;5
        ///E dur;e1;4
        ///A dur;a1;3
        ///D dur;d1;2
        ///G dur;g1;1
        ///C dur;c1;0
        ///F dur;f1;-1
        ///B dur;bé;-2
        ///Es dur;es1;-3
        ///As dur;as1;-4
        ///Des dur;des1;-5
        ///Ges dur;ges1;-6
        ///Ces dur;ces1;-7
        ///ais mol;ais1;7
        ///dis mol;dis1;6
        ///gis mol;gis1;5
        ///cis mol;cis1;4
        ///fis mol;fis1;3
        ///h mol;h;2
        ///e mol;e1;1
        ///a mol;a1;0
        ///d mol;d1;-1
        ///g mol;g1;-2
        ///c mol;c1;-3
        ///f mol;f1;-4
        ///b mol;bé;-5
        ///es mol;es1;-6
        ///as mol;as1;-7
        ///.
        /// </summary>
        internal static string Scales {
            get {
                return ResourceManager.GetString("Scales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bé1;h;-1
        ///h;h;0
        ///his;h;1
        ///hisis;h;2
        ///hisisis;h;3
        ///c1;c1;0
        ///cis1;c1;1
        ///cisis1;c1;2
        ///cisisis1;c1;3
        ///ces1;c1;-1
        ///ceses1;c1;-2
        ///ceseses1;c1;-3
        ///d1;d1;0
        ///dis1;d1;1
        ///disis1;d1;2
        ///disisis1;d1;3
        ///des1;d1;-1
        ///deses1;d1;-2
        ///deseses1;d1;-3
        ///e1;e1;0
        ///eis1;e1;1
        ///eisis1;e1;2
        ///eisisis1;e1;3
        ///es1;e1;-1
        ///eses1;e1;-2
        ///eseses1;e1;-3
        ///f1;f1;0
        ///fis1;f1;1
        ///fisis1;f1;2
        ///fisisis1;f1;3
        ///fes1;f1;-1
        ///feses1;f1;-2
        ///feseses1;f1;-3
        ///g1;g1;0
        ///gis1;g1;1
        ///gisis1;g1;2
        ///gisisis1;g1;3
        ///ges1;g1;-1
        ///geses1;g1;-2
        ///geseses1;g1;-3
        ///a1;a1;0
        ///ais1;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tones {
            get {
                return ResourceManager.GetString("Tones", resourceCulture);
            }
        }
    }
}
